University Parking Website - 3rd Year/App/src/ca377/ca377/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('parkatdcu/',include(('parkatdcu.urls','parkatdcu'),namespace='parkatdcu')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_SUFFIX, document_root=settings.STATIC_ROOT)

University Parking Website - 3rd Year/App/src/ca377/parkatdcu/urls.py
from django.urls import path

from . import views

urlpatterns = [
   path('',views.index,name='index'),
   path('parkatdcu/carparks/',views.carparks,name='carparks'),
   path('bus/campus/',views.campus,name='campus'),
   path('bus/bus/',views.bus,name='bus'),
]

University Parking Website - 3rd Year/App/src/ca377/parkatdcu/models.py
from django.db import models


# Create your models here.
class Campus(models.Model):
   campus_id = models.IntegerField(primary_key=True)
   name = models.CharField(max_length=100)


   def __str__(self):
      return self.name

class Carpark(models.Model):
   carpark_id = models.IntegerField(primary_key=True)
   name = models.CharField(max_length=100)
   campus_id = models.ForeignKey(Campus,on_delete = models.CASCADE)
   spaces = models.IntegerField()
   disabled_spaces = models.IntegerField()

   def __str__(self):
      return self.name

         

University Parking Website - 3rd Year/App/src/ca377/parkatdcu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from parkatdcu.models import Carpark, Campus

from django.conf import settings


import os
import requests
import json

from .models import Campus, Carpark
import requests

from requests.auth import HTTPBasicAuth

# Create your views here.
def index(request):
    context = {}
    return render(request,"parkatdcu/index.html",context)

def carparks(request):

    campus_name = request.GET['campus']

    context = {}
    webservice_base_url = "http://jfoster.pythonanywhere.com/carparks/"

    #Carpark Code

    #Extracts the data from Campus json
    campus_names = Campus.objects.all()

    campus_ids = []

    #Iterates over the campus json data and add the name of each campus in a list if not present
    for ids in campus_names:
        if ids.name not in campus_ids:
            campus_ids.append(ids.name)

    #Allows the user input to be non-case sensitive
    for no_case in campus_ids:
        if campus_name.lower() == no_case.lower():
            campus_name = no_case

    #If the campus is present in the list, execute the following block otherwise go to the else.
    if campus_name in campus_ids:

        #Get the campus names
        campus = Campus.objects.get(name=campus_name)

        #Get the carpark data filtered by campus_id
        carparks = Carpark.objects.filter(campus_id=campus)


        carpark_info = []

        #Iterates over the carpark json
        for carpark in carparks:

            #Access the webservice and extract the data in json format
            webservice_url = webservice_base_url + carpark.name

            realtime_info = requests.get(webservice_url).json()

            #Checks if there are available spaces
            if 'spaces_available' in realtime_info:
                spaces_available = realtime_info['spaces_available']
            else:
                spaces_available = 'not available'

            #Add the data from the carpark and webservice to a list in a dictionary format
            carpark_info.append({
                                'name': carpark.name,
                                'spaces': carpark.spaces,
                                'disabled_spaces': carpark.disabled_spaces,
                                'spaces_available': spaces_available
                                }
                               )
        #If the list is empty, i.e. The campus exists in the api but there is no carpark data available
        if carpark_info == []:
            carpark_info = False

        context['campus'] = campus_name
        context['carparks'] = carpark_info
    
    #If the campus is not present in the list
    else:
        campus_name = "No such campus"
        context['campus'] = campus_name

    return render(request,"parkatdcu/carparks.html",context)

def bus(request):

    bus_stop_location = request.GET['bus']

    context = {}
   
   
    #Extra Functionality: Bus to and from DCU Campus

    #Accessing the GTFS-R api which contains bus journey real time information
    
    webservice_dublin_bus_url = " https://gtfsr.transportforireland.ie/v1/?format=json"

    #Access key embedded in the header
    headers = {
        'Cache-Control': 'no-cache',
        'x-api-key': 'b9162e578e1f4d159e737552a99d107c',
         }


    bus1={}
    response = requests.get(webservice_dublin_bus_url, headers=headers)
    
    bus1 = response.json()
                    
    #Bus data that contains all dcu stops
    dcu_bus = [{
        "id": 1,
        "db_bus": {'Name': 'DCU Ballymun Road, stop 37',
                   'Number': '8220DB000037'}},
    
       {"id" : 2, 
        "db_bus": {'Name': 'DCU Helix, stop 7571',
                   'Number': '8220DB007571'}},

       {"id": 3,
        "db_bus": {'Name':'DCU',
                   'Number': '8220B1350201'}},

       {"id": 4,
        "db_bus": {'Name': 'DCU, stop 4680',
                   'Number': '8220DB004680'}},

       {"id": 5,
        "db_bus": {'Name': 'St Pats, Clonturk Park, Drumcondra Road, stop 80283',
                   'Number': '8220DB000021'}},

       {"id": 6,
        "db_bus": {'Name': 'DCU St Patrick’s, stop 45',
                   'Number': '8220DB000045'}},

       {"id": 7,
        "db_bus": {'Name': 'DCU St Patrick’s, stop 7602',
                   'Number': '8220DB07602'}},

       {"id": 8,
        "db_bus": {'Name': 'DCU Collins Avenue, stop 81909',
                   'Number': '8220DB001644'}},
        
       {"id": 9,
        "db_bus": {'Name': 'DCU Collins Avenue, stop 81910',
                   'Number': '8220DB001646'}}
    ]

    
    Glasnevin = ['8220DB000037','8220DB007571', '8220B1350201', '8220DB004680', '8220DB001644', '8220DB001646']
    St_Pats = ['8220DB000021','8220DB000045', '8220DB07602']


    if bus_stop_location == "Glasnevin":
        bus_stop_location = Glasnevin
    elif bus_stop_location == "St. Pats":
        bus_stop_location = St_Pats
    else:
        bus_stop_location = "No Such Campus"
    
    context["Bus"] = bus_stop_location
    import sys

    #Trip Id and Routes

    #Txt file which contains the information about the trips
    trips = os.path.join(settings.BASE_DIR, "../../data/trips.txt")

    a = []

    #Opens trips.txt
    with open(trips) as f:
        trip = f.readlines()
        i = 0
        #Iterating over each line and putting it in a list and removing the "\n"
        while i < len(trip):
            location = trip[i].split("\n")
            a.append(location)
            i = i + 1


    o = 0

    location_id = []

    #Putting the data from the txt in a manageable list for extraction
    while o < len(a):
        locator = a[o][0].split(",")
        location_id.append({
        
        "Id": o,
        "Location_Route": {
            "Route_Id": locator[0][1:len(locator[0]) - 1],
            "Route_Number": locator[2][1:len(locator[2]) - 1],
            "Location_name": locator[4][1:len(locator[4]) - 1]
            }})
        o = o + 1


    #Bus Routes

    #Txt file which contains the information about the routes
    routes = os.path.join(settings.BASE_DIR, "../../data/routes.txt")

    route_id = []
    #Opens routes.txt
    with open(routes) as l:
        route = l.readlines()
        i = 0
        #Iterating over each line and putting it in a list and removing the "\n"
        while i < len(route):
            number_bus = route[i].split(",")
           #Putting the data from the txt in a manageable list for extraction
            route_id.append({
                "Id": i,
                "Bus_Route": {
                "Route_Id": number_bus[0][1:len(number_bus[0]) - 1],
                "Bus_Number": number_bus[2][1:len(number_bus[2]) - 1],
                "Location_Name": number_bus[3][1:len(number_bus[3]) - 1]
                }})
            i = i + 1

    i = 0

    route_data = []
    location_data = []
    bus_departures = []

    #Search throught the json data extracted from the api starting from the entity key
    for location in bus1['entity']:
        #Iterate through the bus stop data list to find all the stop available at the current time
        for dcu in dcu_bus:
            #If the bus is available put it in a list
            if dcu['db_bus']['Number'] in str(location) and location['id'] not in str(bus_departures):
                bus_departures.append(location)
                #Search through the data extracted from the trips.txt
                for data_location in location_id:
                    #If the route_number matches the location id //trip_id(trips.txt) == id(GTFS-r JSON)\\ and  the id is not already in the list put it in the list as a dictionary. Removes duplicates
                    if data_location['Location_Route']['Route_Number'] == location['id'] and location['id'] not in str(location_data):
                        location_data.append({ 
                            "Id": i,       
                            "Location_Route": {
                                "Route_Id": data_location['Location_Route']['Route_Id'],
                                "Route_Number": data_location['Location_Route']['Route_Number'],
                                "Location_name": data_location['Location_Route']['Location_name']

                            }})
                        i = i + 1

    i = 0

    #Search through the data extracted from routes.txt
    for data_route in route_id:
        #Iterates over the new data extracted from location_id
        for data_location_tailored in location_data:
            #If the two routes match // route_Id(route.txt) == route_Id(location_data) \\ and the Route_Id is not already in the list, add it to the list as a dictionary
            if data_route['Bus_Route']['Route_Id'] == data_location_tailored['Location_Route']['Route_Id'] and data_route['Bus_Route']['Route_Id'] not in str(route_data):
                route_data.append({                
                "Id": i,
                "Bus_Route": {
                    "Route_Id": data_route['Bus_Route']['Route_Id'],
                    "Bus_Number": data_route['Bus_Route']['Bus_Number'],                    
                    }})
                i = i + 1

    roster = []
    i = 0

    #Txt file which contains the information about the stop schedules
    stop_times = os.path.join(settings.BASE_DIR, '../../data/stop_times_dcu_only.txt')

    #Search through the data extracted from stop_times_dcu_only.txt
    with open(stop_times) as stop:
        schedule = stop.readlines()
        #Iterate over the data extracted from stop_times_dcu_only.txt and separate it by the ","
        for each in schedule:
            part = each.split(",")
            #if the trip_id is in location_data dictionary and the stop_id is in dcu_bus and the trip_id is not already in the roster dictionary // avoid duplicate trips

University Parking Website - 3rd Year/App/src/ca377/parkatdcu/templates/bus/bus.html
{% load static %}
{% load filter %}

<link rel="stylesheet" type="text/css" href="{% static 'parkatdcu/style.css' %}">

<div class="title">
<ul>
<li><a href="{% url 'parkatdcu:index' %}">Carpark Information</a></li>
<li><a href="{% url 'parkatdcu:campus' %}">Bus Information</a></li>
<li><a class="a_no_border" href="https://loop.dcu.ie/mod/page/view.php?id=1362396" target="_blank">My DCU - Student</a></li>
<li><a href="https://www.dcu.ie/iss/staff-my-page" target="_blank">My DCU - Staff</a></li>
<li><a href="https://www.dcu.ie/library" target="_blank">Library</a></li>
<li><a href="https://loop.dcu.ie" target="_blank">Loop</a></li>
</ul>
</div>


<img class="logo" src = "{% static 'parkatdcu/images/DCU_logo.png' %}" alt= "dcu_logo" height = "128px" width = "120px">

<h1 class="title2">Bus Time Information</h1>

<div class = "bus_align">
<div class = "bus">
<h2>Departures from DCU</h2>
{% for location in Data_Bus %}
  {% for id in  location.trip_update.stop_time_update %}
    {% for bus in DCU %}
      {% if id.stop_id == bus.db_bus.Number and id.stop_sequence == 1 and id.schedule_relationship == "SCHEDULED" and id.stop_id in Bus %}
        <p class = "underline">Bus Information: </p>
        {% for locator in Location %}
          {% if locator.Location_Route.Route_Number == location.trip_update.trip.trip_id %}
            <p><b>Location Name: </b>{{ locator.Location_Route.Location_name }}</p>
          {% endif %}
        {% endfor %}
        {% for route in Route %}
          {% if route.Bus_Route.Route_Id == location.trip_update.trip.route_id %}
            <p><b>Bus Number: </b>{{ route.Bus_Route.Bus_Number }}</p>
          {% endif %}
        {% endfor %}
        <p><b>Time: </b> {{ location.trip_update.trip.start_time }}</p>
        <p><b>Bus Stop: </b>{{ bus.db_bus.Name }}</p><br>
      {% endif %}
    {% endfor %}
  {% endfor %}
{% endfor %}
</div>

<div class = "bus1">

<h2>Bus Arrivals at DCU stops</h2>
{% for location in Data_Bus %}
  {% for id in  location.trip_update.stop_time_update %}
    {% for bus in DCU %}
      {% for layout in Roster %}
        {% if location.trip_update.trip.trip_id == layout.Schedule.Route_Number and id.stop_sequence|integer == layout.Schedule.Sequence|integer and id.stop_id in Bus %}
          {% if id.stop_id == bus.db_bus.Number and id.stop_sequence|integer != 1 and id.schedule_relationship == "SCHEDULED" %}
            <p class = "underline">Bus Information: </p>
            {% for locator in Location %}
              {% if locator.Location_Route.Route_Number == location.trip_update.trip.trip_id %}
                <p><b>Route Name: </b>{{ locator.Location_Route.Location_name }}</p>
              {% endif %}
            {% endfor %}
            {% for route in Route %}
              {% if route.Bus_Route.Route_Id == location.trip_update.trip.route_id %}
                <p><b>Bus Number: </b>{{ route.Bus_Route.Bus_Number }}</p>
              {% endif %}
            {% endfor %}
            {% for layout in Roster %}
              {% if location.trip_update.trip.trip_id == layout.Schedule.Route_Number and id.stop_sequence|integer == layout.Schedule.Sequence|integer %}
                <p><b>Time: </b>{{ layout.Schedule.Arrival|real:id.arrival.delay }}</p>
              {% endif %}
            {% endfor %}
            <p><b>Location: </b>{{ bus.db_bus.Name }}</p><br>
          {% endif %}
        {% endif %}
      {% endfor %}
    {% endfor %}
  {% endfor %}
{% endfor %}
{% for layout in Roster %}
  {% if layout.Schedule.Route_Number in No_Delay and layout.Schedule.Route_Id in Bus %}
    {% for locator in Location %}
      {% if locator.Location_Route.Route_Number == layout.Schedule.Route_Number %}
        <p class = "underline">Bus Information</p>
        <p><b>Location Name: </b>{{ locator.Location_Route.Location_name }}</p>
      {% endif %}
    {% endfor %}
      {% for route in Route %}
        {% if route.Bus_Route.Route_Id in layout.Schedule.Route_Number %}
          <p><b>Bus Number: </b>{{ route.Bus_Route.Bus_Number }}</p>
        {% endif %}
      {% endfor %}
      <p><b>Time: </b>{{ layout.Schedule.Arrival }}</p>
      {% for bus in DCU %}
        {% if bus.db_bus.Number == layout.Schedule.Route_Id %}
          <p><b>Bus Stop: </b>{{ bus.db_bus.Name }}</p> <br><br>
        {% endif %}
      {% endfor %}
  {% endif %}
{% endfor %}
</div>
</div>

<div class="button1"><div class="button"><input type="button" value="Back" onclick=location.href="{% url 'parkatdcu:campus' %}"></div></div>

<footer class = "bottom">

  <div class="left">
  <ul>
  <li><a href="http://www.dcu.ie/studentapps" target="_blank">Student Apps</a></li>
  <li><a href="http://www.dcu.ie/staff" target="_blank">Staff Apps</a></li>
  <li><a href="http://loop.dcu.ie/" target="_blank">Loop</a></li>
  <li><a href="https://www.dcu.ie/info/information-dcu-disclaimer" target="_blank">Disclaimer</a></li>
  </ul>
  </div>
  <div class="left">
  <ul>
  <li><a href="http://login.mail.dcu.ie/" target="_blank">Student Email</a></li>
  <li><a href="http://apps.dcu.ie/" target="_blank">Staff Email</a></li>
  </ul>
  </div>
  <div class="left">
  <ul>
  <li><a href="https://www.dcu.ie/iss/policies-privacy-and-cookies-statement-information-systems-services" target="_blank">Privacy and Cookies</a></li>
  <li><a href="https://www.dcu.ie/marketing/contact-communications-marketing" target="_blank">Contact Us</a></li>
  </ul>
  </div>
  </div>
  
  <div class = "social_position">
  <div class = "social_media">
  <a href="https://www.facebook.com/DCU" target="_blank">
  <img src="{% static 'parkatdcu/images/facebook.png' %}" alt="Facebook Logo" height="27" width="27"></a>
  </div>
  <div class = "social_media">
  <a href="https://twitter.com/DCU/" target="_blank">
  <img src="{% static 'parkatdcu/images/twitter.png' %}" alt="Twitter Logo" height="27" width="27"></a>
  </div>
  <div class = "social_media">
  <a href="http://www.youtube.com/user/DublinCityUniversity" target="_blank">
  <img src="{% static 'parkatdcu/images/youtube.png' %}" alt="Youtube Logo" height="27" width="27"></a>
  </div>
  <div class = "social_media">
  <a href="https://www.instagram.com/dublincityuniversity/" target="_blank">
  <img src="{% static 'parkatdcu/images/instagram.png' %}" alt="Instagram Logo" height="27" width="27"></a>
  </div>
  </div>
  
  <div class="Other_right">
  <div class="Other">
  <li><a href="http://www.thehelix.ie/">
  <img src="{% static 'parkatdcu/images/helix.png' %}" alt = "Helix Logo"></a></li>
  </div>
  <div class="Other">
  <li><a href="http://www.esf.ie/">
  <img src="{% static 'parkatdcu/images/Irelands-EU-S-IFP-2014-2020.jpg' %}" alt="Irelands EU S IFP Logo"></a></li>
  </div>
  <div class="Other">
  <li><a href="http://www.esf.ie/">
  <img src="{% static 'parkatdcu/images/eu_image.jpg' %}" alt="EU logo"></a></li>
  </div>
  </div>
  
  </footer>

University Parking Website - 3rd Year/App/src/ca377/parkatdcu/templates/bus/campus.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'parkatdcu/style.css' %}">

<script type="text/javascript">
    function loading() {
        let text = document.getElementById("disappear");
        if(text.style.display === "none"){
            text.style.display = "block";
        } else {
            text.style.display = "none";
        }
        document.getElementsByClassName("positioning")[0].style.display = "block";

        //https://stackoverflow.com/questions/58311325/displaying-spinner-onclick
        //https://stackoverflow.com/questions/55442477/make-text-appear-disappear-on-button-click
    };

  </script>

<div class="title">
<ul>
<li><a href="{% url 'parkatdcu:index' %}">Carpark Information</a></li>
<li><a class="a_no_border" href="https://loop.dcu.ie/mod/page/view.php?id=1362396">My DCU - Student</a></li>
<li><a href="https://www.dcu.ie/iss/staff-my-page">My DCU - Staff</a></li>
<li><a href="https://www.dcu.ie/library">Library</a></li>
<li><a href="https://loop.dcu.ie">Loop</a></li>
</ul>
</div>


<img class="logo" src = "{% static 'parkatdcu/images/DCU_logo.png' %}" alt= "dcu_logo" height = "128px" width = "120px">

<h1 class="title2">Welcome to BusStopAtDCU</h1>
<div class="campus">
<h2 class="black">Find Campus</h2>
<div class = "form">
<form id = "disappear" action="{% url 'parkatdcu:bus' %}" method="gcdet" }">
    <select name="bus" size = "2" multiple><br>
    <option name="bus">Glasnevin</option>
    <option name="bus">St. Pats</option>
    </select>
    <div class="button2"><input type="submit" value="Go" onclick="loading()"></div>
</form>
</div>
</div>
<div class="positioning">
    <div class="loading_animation">
    </div>
    <p class = "spin_message">Please Wait, Retrieving Bus Data </p>
</div>



<footer>

<div class="left">
<ul>
<li><a href="http://www.dcu.ie/studentapps">Student Apps</a></li>
<li><a href="http://www.dcu.ie/staff">Staff Apps</a></li>
<li><a href="http://loop.dcu.ie/">Loop</a></li>
<li><a href="https://www.dcu.ie/info/information-dcu-disclaimer">Disclaimer</a></li>
</ul>
</div>
<div class="left">
<ul>
<li><a href="http://login.mail.dcu.ie/">Student Email</a></li>
<li><a href="http://apps.dcu.ie/">Staff Email</a></li>
</ul>
</div>
<div class="left">
<ul>
<li><a href="https://www.dcu.ie/iss/policies-privacy-and-cookies-statement-information-systems-services">Privacy and Cookies</a></li>
<li><a href="https://www.dcu.ie/marketing/contact-communications-marketing">Contact Us</a></li>
</ul>
</div>
</div>

<div class = "social_position">
<div class = "social_media">
<a href="https://www.facebook.com/DCU" target="_blank">
<img src="{% static 'parkatdcu/images/facebook.png' %}" alt="Facebook Logo" height="27" width="27"></a>
</div>
<div class = "social_media">
<a href="https://twitter.com/DCU/" target="_blank">
<img src="{% static 'parkatdcu/images/twitter.png' %}" alt="Twitter Logo" height="27" width="27"></a>
</div>
<div class = "social_media">
<a href="http://www.youtube.com/user/DublinCityUniversity" target="_blank">
<img src="{% static 'parkatdcu/images/youtube.png' %}" alt="Youtube Logo" height="27" width="27"></a>
</div>
<div class = "social_media">
<a href="https://www.instagram.com/dublincityuniversity/" target="_blank">
<img src="{% static 'parkatdcu/images/instagram.png' %}" alt="Instagram Logo" height="27" width="27"></a>
</div>
</div>

<div class="Other_right">
<div class="Other">
<li><a href="http://www.thehelix.ie/">
<img src="{% static 'parkatdcu/images/helix.png' %}" alt = "Helix Logo"></a></li>
</div>
<div class="Other">
<li><a href="http://www.esf.ie/">
<img src="{% static 'parkatdcu/images/Irelands-EU-S-IFP-2014-2020.jpg' %}" alt="Irelands EU S IFP Logo"></a></li>
</div>
<div class="Other">
<li><a href="http://www.esf.ie/">
<img src="{% static 'parkatdcu/images/eu_image.jpg' %}" alt="EU logo"></a></li>
</div>
</div>

</footer>